name: Cross-compile Windows
description: Install MinGW, CMake, Configure and Build Windows Project on Linux

inputs:
  target:
    required: true
    type: string

  build-dir:
    required: false
    default: build
    type: string

  project-dir:
    description: Project base directory
    required: false
    default: .
    type: string  

  build-type:
    required: false
    default: Release
    type: string

runs:
  using: composite
  steps:
    - name: Install MinGW and CMake
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y mingw-w64 cmake make

    - name: Configure
      shell: bash
      run: |
        cmake \
          -S ${{ inputs.project-dir }} -B ${{ inputs.build-dir }} \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
          -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
          -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}

    - name: Build
      shell: bash
      run: |
        cmake \
          --build ${{ inputs.build-dir }} \
          --config ${{ inputs.build-type }} \
          --target ${{ inputs.target }}
  